'use client';
import { useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { formatNumber, priceShort, toFa } from '@/lib/persian';
import { PageHeader, Section, Empty, Field } from './ui';
import { Modal, ErrorText } from './inputs';
import { useSaver } from './useSaver';
import Icon from './Icon';

export default function ColleaguesClient({ colleagues }) { const [q, setQ] = useState(''); const [modal, setModal] = useState(false); const [edit, setEdit] = useState(null); const list = useMemo(() => colleagues.filter((x) => !q || `${x.name} ${x.showroom} ${x.city} ${(x.inventory || []).map((c) => c.brand + c.model).join(' ')}`.toLowerCase().includes(q.toLowerCase())), [colleagues, q]); return <><PageHeader title="شبکه همکاران" subtitle="خودرو را مستقیم پیدا کن، واسطهٔ اضافه را حذف کن"><button className="btn-primary" onClick={() => { setEdit(null); setModal(true); }}><Icon name="plus" /> افزودن همکار</button></PageHeader><div className="card mb-5 p-3"><div className="relative"><Icon name="search" className="absolute right-3 top-1/2 -translate-y-1/2 text-ink-mute" /><input className="input pr-10" value={q} onChange={(e) => setQ(e.target.value)} placeholder="جستجوی نمایشگاه، شهر یا مدل…" /></div></div><div className="grid gap-4 lg:grid-cols-2">{list.map((c) => <div key={c._id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black">{c.showroom || c.name}</h2><div className="mt-1 text-sm text-ink-mute">{c.name} · {c.city || 'شهر نامشخص'} · {c.phone || 'تلفن ندارد'}</div></div><div className="flex gap-2"><a href={`tel:${c.phone}`} className="btn-ghost px-3"><Icon name="phone" size={17} /></a><button className="btn-ghost px-3" onClick={() => { setEdit(c); setModal(true); }}><Icon name="edit" size={17} /></button></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[440px] text-sm"><thead><tr className="text-right text-ink-mute"><th className="py-2">خودرو</th><th>سال</th><th>کارکرد</th><th>قیمت</th></tr></thead><tbody>{(c.inventory || []).map((v, i) => <tr key={i} className="border-t border-line"><td className="py-2 font-bold">{v.brand} {v.model} <span className="font-medium text-ink-mute">{v.color}</span></td><td className="num">{toFa(v.year)}</td><td className="num">{formatNumber(v.mileage)}</td><td className="num font-bold">{priceShort(v.price)}</td></tr>)}</tbody></table></div><div className="mt-3 text-sm font-bold text-plate">{toFa((c.inventory || []).length)} خودرو در شبکه</div></div>)}{!list.length && <Empty>همکاری پیدا نشد.</Empty>}</div><Modal open={modal} onClose={() => setModal(false)} title={edit ? 'ویرایش همکار' : 'افزودن همکار'} wide><ColleagueForm initial={edit} onDone={() => setModal(false)} /></Modal></> }
function ColleagueForm({ initial, onDone }) { const [f, setF] = useState({ name: '', showroom: '', phone: '', city: '', address: '', ...(initial || {}), inventory: initial?.inventory || [] }); const s = useSaver(); const set = (k, v) => setF({ ...f, [k]: v }); const add = () => set('inventory', [...f.inventory, { brand: '', model: '', year: 1402, color: '', mileage: 0, price: 0 }]); const del = (i) => set('inventory', f.inventory.filter((_, j) => j !== i)); const upd = (i, k, v) => set('inventory', f.inventory.map((x, j) => j === i ? { ...x, [k]: v } : x)); return <form onSubmit={(e) => { e.preventDefault(); if (!f.name) return; s.run(async () => { if (initial?._id) await api(`/api/colleagues/${initial._id}`, 'PATCH', f); else await api('/api/colleagues', 'POST', f); onDone?.(); }); }} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="نام همکار *"><input className="input" value={f.name} onChange={(e) => set('name', e.target.value)} autoFocus /></Field><Field label="نام نمایشگاه"><input className="input" value={f.showroom || ''} onChange={(e) => set('showroom', e.target.value)} /></Field><Field label="تلفن"><input dir="ltr" className="input text-left" value={f.phone || ''} onChange={(e) => set('phone', e.target.value)} /></Field><Field label="شهر / محدوده"><input className="input" value={f.city || ''} onChange={(e) => set('city', e.target.value)} /></Field></div><div><div className="mb-2 flex items-center justify-between"><b>موجودی همکار</b><button type="button" className="btn-ghost px-3" onClick={add}><Icon name="plus" size={17} /> خودرو</button></div><div className="space-y-2">{f.inventory.map((v, i) => <div key={i} className="grid grid-cols-2 gap-2 rounded-xl bg-paper p-2 sm:grid-cols-7"><input className="input" placeholder="برند" value={v.brand} onChange={(e) => upd(i, 'brand', e.target.value)} /><input className="input" placeholder="مدل" value={v.model} onChange={(e) => upd(i, 'model', e.target.value)} /><input className="input" placeholder="سال" value={v.year} onChange={(e) => upd(i, 'year', Number(e.target.value))} /><input className="input" placeholder="رنگ" value={v.color} onChange={(e) => upd(i, 'color', e.target.value)} /><input className="input" placeholder="کارکرد" value={v.mileage ?? ''} onChange={(e) => upd(i, 'mileage', Number(e.target.value) || 0)} /><input className="input" placeholder="قیمت" value={v.price} onChange={(e) => upd(i, 'price', Number(e.target.value) || 0)} /><button type="button" className="btn-ghost px-3" onClick={() => del(i)}>حذف</button></div>)}</div></div><ErrorText error={s.err} /><button className="btn-primary w-full" disabled={s.busy}>{s.busy ? 'در حال ذخیره…' : 'ذخیره همکار'}</button></form> }
